"""Generate thesis result tables (LaTeX) from genuine evaluation artifacts.

This script is the single, reproducible source for the tables that go into the
thesis. It reads only artifacts that are mutually consistent and genuine:

* ``outputs/results/ablation.json``            -> ``thesis/tables/ablation_main.tex``
* ``outputs/results/statistical_comparison.csv`` (the EfficientNet-vs-Ark+ rows
  only) -> ``thesis/tables/tier2_backbone_comparison.tex``

Why a curated subset and not "every CSV in outputs/results"?
``outputs/results/tiered_predictions.csv`` (and the threshold-sweep /
model-comparison artifacts derived from it) carries a *stale* Tier-1 column:
its ``tier1_prob`` scores an AUC of ~0.78, which contradicts the genuine
MobileNetV2 Tier-1 result in ``ablation.json`` (A1, AUC ~0.92). Until that file
is regenerated with the current evaluation pipeline, the MobileNet/Tiered rows
of the statistical comparison are not trustworthy, so this generator emits only
the EfficientNet-vs-Ark+ comparison (which uses ``tier2_prob`` and *is*
consistent with ``ablation.json``). Never wire stale numbers into the thesis.

Usage::

    python scripts/build_thesis_tables.py
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
RESULTS_DIR = REPO_ROOT / "outputs" / "results"
TABLES_DIR = REPO_ROOT / "thesis" / "tables"

# Comparison label whose rows are consistent with ablation.json (Tier-2 backbones).
TIER2_COMPARISON = "EfficientNetB4 vs Ark+ Swin"

# Per-metric choice of the most appropriate paired significance test.
PVALUE_SOURCE = {
    "AUC": ("p_value_delong", "DeLong"),
    "ACCURACY": ("p_value_mcnemar", "McNemar"),
    "SENSITIVITY": ("p_value_bootstrap", "Bootstrap"),
    "SPECIFICITY": ("p_value_bootstrap", "Bootstrap"),
    "F1": ("p_value_bootstrap", "Bootstrap"),
}

_LATEX_SPECIAL = {
    "&": r"\&",
    "%": r"\%",
    "#": r"\#",
    "_": r"\_",
    "$": r"\$",
}


def tex_escape(text: str) -> str:
    """Escape the LaTeX special characters that appear in our label strings."""
    return "".join(_LATEX_SPECIAL.get(ch, ch) for ch in text)


def fmt(value: float | None, digits: int = 3) -> str:
    """Format a float to fixed decimals, or an em-dash when missing."""
    if value is None:
        return "--"
    return f"{value:.{digits}f}"


def fmt_pvalue(value: float | None) -> str:
    """Format a p-value, collapsing tiny values to ``<0.001``."""
    if value is None:
        return "--"
    if value < 0.001:
        return "$<0.001$"
    return f"{value:.3f}"


def build_ablation_table() -> str:
    """Render the A1-A15 ablation table from the genuine ``ablation.json``."""
    rows = json.loads((RESULTS_DIR / "ablation.json").read_text())
    best_auc = max(r["metrics"]["auc_roc"] for r in rows)

    lines = [
        "% Auto-generated by scripts/build_thesis_tables.py -- do not edit by hand.",
        "% Source: outputs/results/ablation.json (genuine 15/15 evaluation).",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Ablation study over the tiered system (A1--A15) on the NIH "
        r"Chest X-Ray test set. Tier~1 is MobileNetV2 throughout. The best AUC is "
        r"shown in bold. ECE is reported where calibration was evaluated.}",
        r"\label{tab:ablation_main}",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{llllllrrr}",
        r"\toprule",
        r"\textbf{ID} & \textbf{Configuration} & \textbf{Tier 1} & "
        r"\textbf{Tier 2} & \textbf{Routing} & \textbf{Uncertainty} & "
        r"\textbf{AUC} & \textbf{Acc.} & \textbf{ECE} \\",
        r"\midrule",
    ]

    for r in rows:
        m = r["metrics"]
        auc_str = fmt(m["auc_roc"])
        if abs(m["auc_roc"] - best_auc) < 1e-12:
            auc_str = rf"\textbf{{{auc_str}}}"
        cells = [
            tex_escape(r["ablation_id"]),
            tex_escape(r["name"]),
            tex_escape(r["tier1"]),
            tex_escape(r["tier2"]),
            tex_escape(r["routing"]),
            tex_escape(r["uncertainty"]),
            auc_str,
            fmt(m["accuracy"]),
            fmt(m.get("ece")),
        ]
        lines.append(" & ".join(cells) + r" \\")

    lines += [
        r"\bottomrule",
        r"\end{tabular}%",
        r"}",
        r"\end{table}",
        "",
    ]
    return "\n".join(lines)


def build_tier2_comparison_table() -> str:
    """Render the EfficientNet-B4 vs Ark+ Swin head-to-head comparison table.

    Uses only the ``EfficientNetB4 vs Ark+ Swin`` rows of
    ``statistical_comparison.csv`` (genuine, consistent with ablation.json).
    """
    with (RESULTS_DIR / "statistical_comparison.csv").open() as fh:
        rows = [r for r in csv.DictReader(fh) if r["Comparison"] == TIER2_COMPARISON]

    def f(row: dict[str, str], key: str) -> float | None:
        raw = row.get(key, "")
        return float(raw) if raw not in ("", None) else None

    lines = [
        "% Auto-generated by scripts/build_thesis_tables.py -- do not edit by hand.",
        "% Source: outputs/results/statistical_comparison.csv "
        "(EfficientNetB4 vs Ark+ Swin rows).",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Head-to-head comparison of the two Tier-2 backbones "
        r"(EfficientNet-B4 vs.\ Ark+ Swin) on the NIH test set, with paired "
        r"bootstrap 95\% confidence intervals and per-metric significance tests. "
        r"$\Delta$ is Ark+ Swin minus EfficientNet-B4.}",
        r"\label{tab:tier2_backbone_comparison}",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{lcccll}",
        r"\toprule",
        r"\textbf{Metric} & \textbf{EfficientNet-B4 [95\% CI]} & "
        r"\textbf{Ark+ Swin [95\% CI]} & \textbf{$\Delta$ [95\% CI]} & "
        r"\textbf{$p$} & \textbf{Test} \\",
        r"\midrule",
    ]

    for row in rows:
        metric = row["Metric"]
        pkey, ptest = PVALUE_SOURCE.get(metric, ("p_value_bootstrap", "Bootstrap"))
        m1 = f"{fmt(f(row, 'Model1_Score'))} ({fmt(f(row, 'Model1_CI_Lower'))}, {fmt(f(row, 'Model1_CI_Upper'))})"
        m2 = f"{fmt(f(row, 'Model2_Score'))} ({fmt(f(row, 'Model2_CI_Lower'))}, {fmt(f(row, 'Model2_CI_Upper'))})"
        delta = f"{fmt(f(row, 'Delta'))} ({fmt(f(row, 'Delta_CI_Lower'))}, {fmt(f(row, 'Delta_CI_Upper'))})"
        cells = [
            metric.capitalize() if metric != "AUC" else "AUC",
            m1,
            m2,
            delta,
            fmt_pvalue(f(row, pkey)),
            ptest,
        ]
        lines.append(" & ".join(cells) + r" \\")

    lines += [
        r"\bottomrule",
        r"\end{tabular}%",
        r"}",
        r"\end{table}",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    TABLES_DIR.mkdir(parents=True, exist_ok=True)

    targets = {
        "ablation_main.tex": build_ablation_table(),
        "tier2_backbone_comparison.tex": build_tier2_comparison_table(),
    }
    for filename, content in targets.items():
        out = TABLES_DIR / filename
        out.write_text(content)
        print(f"wrote {out.relative_to(REPO_ROOT)} ({len(content.splitlines())} lines)")


if __name__ == "__main__":
    main()
