"""Generate thesis result tables (LaTeX) from genuine evaluation artifacts.

This script is the single, reproducible source for the tables that go into the
thesis. It reads only artifacts that are mutually consistent and genuine:

* ``outputs/results/ablation.json``            -> ``thesis/tables/ablation_main.tex``
* ``outputs/results/statistical_comparison.csv`` (the EfficientNet-vs-Ark+ rows
  only) -> ``thesis/tables/tier2_backbone_comparison.tex``

Why a curated subset and not "every CSV in outputs/results"?
``outputs/results/tiered_predictions.csv`` (and the threshold-sweep /
model-comparison artifacts derived from it) carries a *stale* Tier-1 column:
its ``tier1_prob`` scores an AUC of ~0.78, which contradicts the genuine
MobileNetV2 Tier-1 result in ``ablation.json`` (A1, AUC ~0.92). Until that file
is regenerated with the current evaluation pipeline, the MobileNet/Tiered rows
of the statistical comparison are not trustworthy, so this generator emits only
the EfficientNet-vs-Ark+ comparison (which uses ``tier2_prob`` and *is*
consistent with ``ablation.json``). Never wire stale numbers into the thesis.

Usage::

    python scripts/build_thesis_tables.py
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
RESULTS_DIR = REPO_ROOT / "outputs" / "results"
TABLES_DIR = REPO_ROOT / "thesis" / "tables"

# Comparison label whose rows are consistent with ablation.json (Tier-2 backbones).
TIER2_COMPARISON = "EfficientNetB4 vs Ark+ Swin"

# Per-metric choice of the most appropriate paired significance test.
PVALUE_SOURCE = {
    "AUC": ("p_value_delong", "DeLong"),
    "ACCURACY": ("p_value_mcnemar", "McNemar"),
    "SENSITIVITY": ("p_value_bootstrap", "Bootstrap"),
    "SPECIFICITY": ("p_value_bootstrap", "Bootstrap"),
    "F1": ("p_value_bootstrap", "Bootstrap"),
}

_LATEX_SPECIAL = {
    "&": r"\&",
    "%": r"\%",
    "#": r"\#",
    "_": r"\_",
    "$": r"\$",
}


def tex_escape(text: str) -> str:
    """Escape the LaTeX special characters that appear in our label strings."""
    return "".join(_LATEX_SPECIAL.get(ch, ch) for ch in text)


def fmt(value: float | None, digits: int = 3) -> str:
    """Format a float to fixed decimals, or an em-dash when missing."""
    if value is None:
        return "--"
    return f"{value:.{digits}f}"


def fmt_pvalue(value: float | None) -> str:
    """Format a p-value, collapsing tiny values to ``<0.001``."""
    if value is None:
        return "--"
    if value < 0.001:
        return "$<0.001$"
    return f"{value:.3f}"


def build_ablation_table() -> str:
    """Render the A1-A15 ablation table from the genuine ``ablation.json``."""
    rows = json.loads((RESULTS_DIR / "ablation.json").read_text())
    best_auc = max(r["metrics"]["auc_roc"] for r in rows)

    lines = [
        "% Auto-generated by scripts/build_thesis_tables.py -- do not edit by hand.",
        "% Source: outputs/results/ablation.json (genuine 15/15 evaluation).",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Ablation study over the tiered system (A1--A15). All "
        r"configurations are evaluated on the NIH Chest X-Ray test set except "
        r"A14, which is a zero-shot evaluation on CheXpert. Tier~1 is MobileNetV2 "
        r"throughout. The best AUC is shown in bold. ECE is reported where "
        r"calibration was evaluated.}",
        r"\label{tab:ablation_main}",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{llllllrrr}",
        r"\toprule",
        r"\textbf{ID} & \textbf{Configuration} & \textbf{Tier 1} & "
        r"\textbf{Tier 2} & \textbf{Routing} & \textbf{Uncertainty} & "
        r"\textbf{AUC} & \textbf{Acc.} & \textbf{ECE} \\",
        r"\midrule",
    ]

    for r in rows:
        m = r["metrics"]
        auc_str = fmt(m["auc_roc"])
        if abs(m["auc_roc"] - best_auc) < 1e-12:
            auc_str = rf"\textbf{{{auc_str}}}"
        cells = [
            tex_escape(r["ablation_id"]),
            tex_escape(r["name"]),
            tex_escape(r["tier1"]),
            tex_escape(r["tier2"]),
            tex_escape(r["routing"]),
            tex_escape(r["uncertainty"]),
            auc_str,
            fmt(m["accuracy"]),
            fmt(m.get("ece")),
        ]
        lines.append(" & ".join(cells) + r" \\")

    lines += [
        r"\bottomrule",
        r"\end{tabular}%",
        r"}",
        r"\end{table}",
        "",
    ]
    return "\n".join(lines)


def build_tier2_comparison_table() -> str:
    """Render the EfficientNet-B4 vs Ark+ Swin head-to-head comparison table.

    Uses only the ``EfficientNetB4 vs Ark+ Swin`` rows of
    ``statistical_comparison.csv`` (genuine, consistent with ablation.json).
    """
    with (RESULTS_DIR / "statistical_comparison.csv").open() as fh:
        rows = [r for r in csv.DictReader(fh) if r["Comparison"] == TIER2_COMPARISON]

    def f(row: dict[str, str], key: str) -> float | None:
        raw = row.get(key, "")
        return float(raw) if raw not in ("", None) else None

    lines = [
        "% Auto-generated by scripts/build_thesis_tables.py -- do not edit by hand.",
        "% Source: outputs/results/statistical_comparison.csv "
        "(EfficientNetB4 vs Ark+ Swin rows).",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Head-to-head comparison of the two Tier-2 backbones "
        r"(EfficientNet-B4 vs.\ Ark+ Swin) on the NIH test set, with paired "
        r"bootstrap 95\% confidence intervals and per-metric significance tests. "
        r"$\Delta$ is Ark+ Swin minus EfficientNet-B4.}",
        r"\label{tab:tier2_backbone_comparison}",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{lcccll}",
        r"\toprule",
        r"\textbf{Metric} & \textbf{EfficientNet-B4 [95\% CI]} & "
        r"\textbf{Ark+ Swin [95\% CI]} & \textbf{$\Delta$ [95\% CI]} & "
        r"\textbf{$p$} & \textbf{Test} \\",
        r"\midrule",
    ]

    for row in rows:
        metric = row["Metric"]
        pkey, ptest = PVALUE_SOURCE.get(metric, ("p_value_bootstrap", "Bootstrap"))
        m1 = f"{fmt(f(row, 'Model1_Score'))} ({fmt(f(row, 'Model1_CI_Lower'))}, {fmt(f(row, 'Model1_CI_Upper'))})"
        m2 = f"{fmt(f(row, 'Model2_Score'))} ({fmt(f(row, 'Model2_CI_Lower'))}, {fmt(f(row, 'Model2_CI_Upper'))})"
        delta = f"{fmt(f(row, 'Delta'))} ({fmt(f(row, 'Delta_CI_Lower'))}, {fmt(f(row, 'Delta_CI_Upper'))})"
        cells = [
            metric.capitalize() if metric != "AUC" else "AUC",
            m1,
            m2,
            delta,
            fmt_pvalue(f(row, pkey)),
            ptest,
        ]
        lines.append(" & ".join(cells) + r" \\")

    lines += [
        r"\bottomrule",
        r"\end{tabular}%",
        r"}",
        r"\end{table}",
        "",
    ]
    return "\n".join(lines)


# NIH ChestX-ray14 splits used for the pneumothorax task. The label column
# ("Label") is 1 for pneumothorax, 0 otherwise.
PROCESSED_DIR = REPO_ROOT / "data" / "processed"
SPLIT_FILES = [
    ("Train", "train.csv"),
    ("Validation", "val.csv"),
    ("Calibration", "calibration.csv"),
    ("Test", "test.csv"),
]

# Genuine training configuration. Source: config/base.yaml (training/model/data/
# evaluation sections) and application/services/training_service.py (optimizer).
# These are human-authored constants, transcribed here verbatim.
HYPERPARAMETERS = [
    ("Tier-1 backbone", "MobileNetV2"),
    ("Tier-2 backbone", "EfficientNet-B4 / Ark+ Swin"),
    ("Input resolution", r"$224 \times 224$"),
    ("Optimizer", r"AdamW (weight decay $10^{-4}$)"),
    ("Backbone learning rate", r"$10^{-4}$"),
    ("Classifier-head learning rate", r"$10^{-3}$"),
    ("Batch size", "32"),
    ("Max epochs", "50 (early stopping, patience 7)"),
    ("MC-Dropout passes ($T$)", "20"),
    ("Test-time augmentation passes", "10"),
    ("Escalation threshold ($\\tau$)", r"0.75 (dynamic; window 50, $\delta = 0.05$)"),
    ("Conformal target coverage", r"$1 - \alpha = 0.95$"),
    ("Random seed", "42"),
]


def build_dataset_table() -> str:
    """Render the NIH ChestX-ray14 split statistics from the processed CSVs."""
    import pandas as pd

    body: list[str] = []
    tot_n = tot_pos = tot_neg = 0
    for label, filename in SPLIT_FILES:
        path = PROCESSED_DIR / filename
        if not path.exists():
            continue
        df = pd.read_csv(path)
        n = len(df)
        pos = int(df["Label"].sum())
        neg = n - pos
        tot_n += n
        tot_pos += pos
        tot_neg += neg
        body.append(
            f"{label} & {n:,} & {pos:,} & {neg:,} & {pos / n * 100:.1f}\\% \\\\"
        )
    body.append(r"\midrule")
    body.append(
        f"\\textbf{{Total}} & {tot_n:,} & {tot_pos:,} & {tot_neg:,} & "
        f"{tot_pos / tot_n * 100:.1f}\\% \\\\"
    )

    lines = [
        "% Auto-generated by scripts/build_thesis_tables.py -- do not edit by hand.",
        "% Source: data/processed/{train,val,calibration,test}.csv.",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{NIH ChestX-Ray14 dataset splits used for the pneumothorax "
        r"classification task. The calibration split is held out for conformal "
        r"prediction. Prevalence is the fraction of pneumothorax-positive images.}",
        r"\label{tab:dataset_stats}",
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"\textbf{Split} & \textbf{Images} & \textbf{Pneumothorax} & "
        r"\textbf{Normal} & \textbf{Prevalence} \\",
        r"\midrule",
        *body,
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ]
    return "\n".join(lines)


def build_hyperparameter_table() -> str:
    """Render the training hyperparameter table from the genuine configuration."""
    body = [f"{tex_escape_value(name)} & {value} \\\\" for name, value in HYPERPARAMETERS]
    lines = [
        "% Auto-generated by scripts/build_thesis_tables.py -- do not edit by hand.",
        "% Source: config/base.yaml + application/services/training_service.py.",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Training and inference hyperparameters. The same training "
        r"configuration is shared by both tiers; tier-specific differences are "
        r"limited to the backbone architecture.}",
        r"\label{tab:hyperparameters}",
        r"\begin{tabular}{ll}",
        r"\toprule",
        r"\textbf{Hyperparameter} & \textbf{Value} \\",
        r"\midrule",
        *body,
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ]
    return "\n".join(lines)


def tex_escape_value(text: str) -> str:
    """Escape only the characters that are not already part of a math expression."""
    # Names here may contain '$...$' math; escape bare '&', '%', '#' outside math.
    if "$" in text:
        return text
    return tex_escape(text)


def main() -> None:
    TABLES_DIR.mkdir(parents=True, exist_ok=True)

    targets = {
        "ablation_main.tex": build_ablation_table(),
        "tier2_backbone_comparison.tex": build_tier2_comparison_table(),
        "dataset_stats.tex": build_dataset_table(),
        "hyperparameters.tex": build_hyperparameter_table(),
    }
    for filename, content in targets.items():
        out = TABLES_DIR / filename
        out.write_text(content)
        print(f"wrote {out.relative_to(REPO_ROOT)} ({len(content.splitlines())} lines)")


if __name__ == "__main__":
    main()
